### ISSUE TITLE
Swift compiler options

### ISSUE THREAD

**Issue by rudedogg** [frol/completely-unscientific-benchmarks#20]
Can you try adding the `-whole-module-optimization` flag?

I notice a speedup when using it (1.60s to 1.28 on i7-8700K), but I don't really understand why. I didn't think it would matter since everything is contained in a single file. I guess it works by looking at Foundation (and whatever dependencies you might have) to do optimizations?

Some references if someone wants to dig deeper:
https://swift.org/blog/whole-module-optimizations/

**Comment by frol** [comment]
Indeed! I will update the README for Swift and the stats ASAP

**Comment by rudedogg** [comment]
That was fast! Thanks!
