### ISSUE TITLE
C++ memory results might be a bit misleading

### ISSUE THREAD

**Issue by PMunch** [frol/completely-unscientific-benchmarks#43]
During my work on the Nim version of this code (which it it's most optimised version beats the C++ versions on speed), I did some runs of the C++ code as well. One thing I noticed is that I regularly got 504KiB memory usage, and not the 0.3MiB (so somewhere around the 300KiB mark). I did sometimes see it dip to 376KiB however, so I went to see how often this would happen.

To get lot's of measurements I went with:
```
for i in {0..10000}; do; ~/div/cgmemtime/cgmemtime --force-empty -t ./main-gcc 2>>memtest2; done
```
However I did abort the run after 5826 samples as it was starting to drag on a bit. The average memory consumption of all the runs were 524KiB and the breakdown of samples was as follows:

Memory usage | Occurences
------------ | -------------
376 | 29
380 | 42
500 | 1
504 | 4512
508 | 295
632 | 891
636 | 37
760 | 16
764 | 2
Total Result | 5825

As we can see only 71 of the 5825 runs used less than 500KiB, a mere 1.22%.

Running with the Nim version with manual memory allocation we actually get a better average at 513KiB with a breakdown of:

Memory usage | Occurences
------------ | -------------
500 | 1
504 | 880
508 | 53
632 | 60
636 | 4
760 | 2
Total Result | 1000

And just for comparison the Nim version using the GC get's an average of 899KiB with a breakdown of:

Memory usage | Occurences
------------ | -------------
888 | 868
892 | 48
1016 | 77
1020 | 4
1144 | 3
Total Result | 1000

The speed seems to be affected as well, although not as much:

C++ raw pointers | Nim manual memory | Nim GC
-------------------- | ----------------------- | -------------
0.314 | 0.280 | 0.282
0.241 | 0.190 | 0.193

First row is average speed, second is minimum speed (C++ version run 5825 times, the Nim versions only 1000 times).

**Comment by PMunch** [comment]
Yeah, that's why I used average instead of minimum in all of my testing, normally running 100 runs at a time (works fine  for C++ and Nim, probably wouldn't do it for the slower candidates as it would take a really long time).

**Comment by frol** [comment]
I believe the minimum value is fair enough given the algorithm require a constant amount of allocations between executions. Averaging catches some irrelevant fluctuations.

**Comment by PMunch** [comment]
Yeah but as you say it also will count less if something else had a shared library cached. So you will catch irrelevant fluctuations both ways. Probably shouldn't use an average though, but rather a median.

**Comment by frol** [comment]
If I compile C++, D, and Nim solutions statically I see the following memory footprints stable:

| Solution | time, seconds | memory, MB |
| - | - | - |
| C++ | 0.208 | 0.248 |
| D (no-RT) | 0.198 | 0.248 |
| Nim (manual) | **0.179** (OH MY GOD) | 0.376 |

**Comment by PMunch** [comment]
Really interesting, wasn't expecting to see much more speed increase on this without having to use some really dirty tricks. Reran on my machine all three versions with static linking.
Speed, first is average, second is median, third is min:

C++ raw | Nim manual | Nim GC
------------- | -------------------- | ------------
0.243     | 0.211              | 0.217
0.242     | 0.210              | 0.215
0.227     | 0.197              | 0.199

Memory, order same as before:
C++ raw | Nim manual | Nim GC
------------- | -------------------- | ------------
249         | 376                | 760
248         | 376                | 760
248         | 376                | 760

Very interesting to see that Nim with garbage collector is able to keep up this well, albeit using a bit more memory.

**Comment by PMunch** [comment]
I still think median is the way to go though, it's more "correct" for this kind of thing.

**Comment by mratsim** [comment]
It's probably less accurate but Kostya uses this short ruby script for memory + time tracking: https://github.com/kostya/benchmarks/blob/master/xtime.rb

Given how fast the tasks are it might not be precise enough though.

**Comment by PMunch** [comment]
Hmm, interesting. I tried to run the `fast` version of the Nim code using the default garbage collector, and it achieved the same 376KiB as the manual memory version, but it does so using 0.535s (median again, 100 samples). So it appears you can choose (compared to the manual version), near-perfect memory usage, or near-perfect speed, good to know.

**Comment by frol** [comment]
I have just updated the scoreboards!

**Comment by frol** [comment]
I still believe that the minimum memory consumption is the best way to estimate the solution memory footprint since the memory footprints of statically linked solutions do not fluctuate (i.e. the fluctuations are caused by something external to the solution itself).
