### ISSUE TITLE
Provide simple runtime-enabled D version

### ISSUE THREAD

**Issue by nervecenter** [frol/completely-unscientific-benchmarks#49]
I went through translating the Java version to simple, straightforward D with runtime and GC. Compiled with DMD on my 2013 Macbook Pro with a dual-core i5, I get about 0.61s - 0.65s real runtimes.

This one is simple enough to be used with `rdmd`:

`rdmd treap_gc.d`
`time rdmd treap_gc.d`

Remember that the first `rdmd` run compiles, so it will take longer.

With -O:

`rdmd -O treap_gc.d`
`time -O rdmd treap_gc.d`

times reduce to about 0.46s - 0.48s.

[treap_gc_d.tar.gz](https://github.com/frol/completely-unscientific-benchmarks/files/2013676/treap_gc_d.tar.gz)

Feel free to compile with LDC and all sorts of options when testing.

Edit: Apologies, I see there's already a runtime-enabled version, but I don't see the code that was used. I'll leave this issue up in case it proves useful.

**Comment by frol** [comment]
/cc @edmundsmith 

I am not familiar with D at all, so I am a bit confused about differences between `rdmd` and `ldc2`. Are  those two completely different compilers? Which one is the mainstream? I used `ldc2` per the instructions that were provided in the original PR.

**Comment by nervecenter** [comment]
There are three compilers for D.

DMD is the reference compiler, run with `dmd`. It has a compile-to-memory-and-run-immediately option called with `rdmd`. This allows one to run D code as if it were a script:

`$ rdmd helloworld.d
Hello world!`

LDC is the LLVM compiler. This is implemented by a separate team, and uses LLVM as the backend in order to benefit from LLVM's optimizations.

GDC is the GNU D Compiler. Again, a separate team. It uses the GNU backend and behaves like most other GNU Compiler Collection compilers. GDC is currently on the way to being included in the `gcc` package for various Linux distributions by default.

**Comment by nervecenter** [comment]
Gonna close this since I went ahead and added this code, it's simply up to the maintainers to test it and post results.
