### ISSUE TITLE
Different C compilers for Nim output

### ISSUE THREAD

**Issue by hlaaftana** [frol/completely-unscientific-benchmarks#50]
As C++ is tested with different compilers, maybe Nim's tuned implementations could be tested with different C compilers too.

**Comment by frol** [comment]
Are there more than one complete Nim compiler? C++ is tested on the most popular open C++ compilers. Those are mature and popular on their respective platforms. That is, I don't want to turn this benchmark into an endless list of tons of variations. BTW, you can always just test whatever alternative solutions and configurations and compare them by the relative slowdown to get an idea of how fast your solution or configuration is.

**Comment by frol** [comment]
Oh, I just got what you meant! Well, that will only show the difference between C compilers... That is quite orthogonal to Nim itself. I imagine someone interested specifically in Nim would find it informative to see a separate blog post or whatever comparing tons of different GCs and C compilers out there.
