### ISSUE TITLE
D: LTO with LDC

### ISSUE THREAD

**Issue by JohanEngelen** [frol/completely-unscientific-benchmarks#54]
Nice that D is included.

For the compilation flags for LDC: turning on LTO is best done by passing the flag directly to LDC (i.e. not to the C compiler with `-Xcc`).
Better flags are: `-flto=full -defaultlib=phobos2-ldc-lto,druntime-ldc-lto`
With those flags, you get LTO also for the standard library and runtime library (although it is not much used in the program).

**Comment by frol** [comment]
I will check and update the README. Thanks!

**Comment by frol** [comment]
FYI.

`-flto=full` instead of `-Xcc -flto`, just as expected, didn't change anything in terms of the performance.

`-defaultlib=phobos2-ldc-lto,druntime-ldc-lto` caused a compilation error:

```
$ ldc2 main_naive_pointers.d -O3 -release -flto=full -defaultlib=phobos2-ldc-lto,druntime-ldc-lto -of=main_naive_pointers-ldc
/usr/bin/ld: cannot find -lphobos2-ldc-lto-shared
/usr/bin/ld: cannot find -ldruntime-ldc-lto-shared
collect2: error: ld returned 1 exit status
Error: /usr/bin/gcc failed with status: 1
```

**Comment by JohanEngelen** [comment]
@frol Ah, I guess `-shared` is default on your platform. `-static` should fix that and enable full LTO with the standard/runtime library (`-defaultlib=phobos2-ldc-lto,druntime-ldc-lto`).

**Comment by JohanEngelen** [comment]
(performance-wise, I also don't expect too much of LTO. The benchmark is not making use of the stdlib extensively)

**Comment by frol** [comment]
> Ah, I guess `-shared` is default on your platform.

I don't think so as once I compile it without the `defaultlib` I get the following binary:

```
$ ldd main_naive_pointers-ldc
        linux-vdso.so.1 (0x00007fff995e2000)
        libphobos2-ldc-shared.so.79 => /usr/lib/libphobos2-ldc-shared.so.79 (0x00007fb157a94000)
        libdruntime-ldc-shared.so.79 => /usr/lib/libdruntime-ldc-shared.so.79 (0x00007fb157789000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007fb157581000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fb15737d000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fb15715f000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007fb156dca000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007fb156a0e000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fb1567f6000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fb1582fe000)
```

In any case, it works fine as it is now.

**Comment by JohanEngelen** [comment]
Exactly, `-shared` is default for you and thus things link with `libphobos2-ldc-shared.so.79` (instead of there not being a mention of libphobos or libdruntime)

**Comment by JohanEngelen** [comment]
> In any case, it works fine as it is now.

For the single source file case that is being tested, LTO can only do _very_ little. But with LTO'd druntime+stdlib, there are large potential performance improvements (when the stdlib is used); well worth the extra size in the packages that we release :)

In any case, for this particular benchmark, I don't expect large differences with this extra niceness.
Just thought I should mention the best way of using LTO.
