### ISSUE TITLE
Improve Go implementation 

### ISSUE THREAD

**Issue by drorafek** [frol/completely-unscientific-benchmarks#58]
I have two suggestions regarding to the Go implementation:
1. Use `int32` and not `int`, since Go use `int64` for 64-bit GOARCHes
2. Use native `println` instead of importing `fmt` package for printing

**Comment by yml** [comment]
@drorafek have you tried any of this ?
I tried `1.` and I have not seen a great speed up.

I am guessing that the performance issue we are hitting into is that GO GC compiler does not support TCO.

* https://github.com/golang/go/issues/22624
* https://medium.com/@felipedutratine/iterative-vs-recursive-vs-tail-recursive-in-golang-c196ca5fd489

Benchmarking the optimised version GO show that we spend a bit less that 60 in the splitBinary function.

**Comment by drorafek** [comment]
What about memory footprint? my guess is that it should use half of the memory for holding the numbers... but maybe I'm wrong 
And the reason I suggested `2.` was to reduce the binary size.

**Comment by frol** [comment]
1. This didn't improve performance at all (neither RAM usage nor execution time). The only effect I see is that it made the code less readable due to explicit `int32(...)` typing.
2. This dropped the binary size from 1.2MB to 0.7MB! I will apply the change.

**Comment by frol** [comment]
Well, after digging into `println` vs `fmt.Println`:

> Thus, they [`print` and `println`] are useful to developers, because they lack dependencies (being built into the compiler), but not in production code. It also important to note that print and println report to stderr, not stdout.
>
> The family provided by fmt, however, are built to be in production code. They report predictably to stdout, unless otherwise specified. They are more versatile (fmt.Fprint* can report to any io.Writer, such as os.Stdout, os.Stderr, or even a net.Conn type.) and are not implementation specific.

Thus, I won't apply the change since it will be inconsistent with other implementations.

**Comment by data-man** [comment]
> it will be inconsistent with other implementations

D and Pascal uses writeln.
Nim uses stdout.write.

**Comment by frol** [comment]
@data-man All the implementations use stdout, so Go should also output to stdout, but `println` outputs to stderr.
