### ISSUE TITLE
Crystal lang implementation

### ISSUE THREAD

**Issue by cfsamson** [frol/completely-unscientific-benchmarks#62]
Hi. I made a basic implementation in [Crystal](https://crystal-lang.org) if you want it. No special tuning.
[unscientific.txt](https://github.com/frol/completely-unscientific-benchmarks/files/2237931/unscientific.txt)

Would be fun to see how it stacks up to the rest on the same hardware and I think the language is getting more and more attention these days and fits nicely together with the other languages you have benchmarked.

**Comment by frol** [comment]
@cfsamson Nice! I will give it a go later today!

**Comment by cfsamson** [comment]
cool, just remember to compile with --release 👍 

It's based of the Javascript version, so I guess there are optimizations to be made, but I'll leave that for another time.

**Comment by frol** [comment]
Can you provide the command to compile in a release mode?

**Comment by cfsamson** [comment]
crystal build unscientific.cr --release --no-debug

You will have to rename the file to .cr as i could only upload .txt.

**Comment by cfsamson** [comment]
You might want to do "crystal tool format unscientific.cr" first if the intendation etc gets messed so it looks proper again.

**Comment by frol** [comment]
Crystal did pretty well on the benchmark and I gave it max scores for "expressiveness" and "maintenance complexity" (it is the first such case on this benchmark!)

**Comment by cfsamson** [comment]
Thanks for the nice reply! Yes thats why I like Crystal, and hope more people gives it a go :)

**Comment by girng** [comment]
@cfsamson ty for doing the crystal benchmark sir.

@frol ty for adding it as well. awesome to see it here =]

**Comment by cfsamson** [comment]
@frol Hi. I've been playing around with this a bit, and I found a "tuned" version that showed an increased performance on my pc of approx 15 % while keeping the exact same algorithm. The CPU is quite old though so it might be more or less on a different PC. The code is here:

[unscientific2.txt](https://github.com/frol/completely-unscientific-benchmarks/files/2291916/unscientific2.txt)

I added a generic intel cpu as target in the build options that should be quite portable still. I guess it could perform better if we set the exact generation of the cpu on the machine it's running on (similar to what march=native does in a traditional C compiler). 

However, it should perform measurably better with the supplied options. If you have time it would be fun to see how it does on your setup

Compiler options:
> crystal build --mcpu core2 unscientific2.cr --release --no-debug

**Comment by frol** [comment]
@cfsamson I am sorry, I will not be able to look into it before September 1st. I will try to get back to it as soon as I have an opportunity. Please, ping me in September.

**Comment by cfsamson** [comment]
No problem 👍

**Comment by frol** [comment]
@cfsamson I am sorry for the long delay. I have just had time to test your tuned solution and it does not show any measurable performance improvement on my setup (Core i7-4710HQ, Arch Linux, x64, Crystal 0.26.1). `--mcpu core2` does not affect the performance either.

**Comment by cfsamson** [comment]
@frol Ok, thanks for givint it a go. Sorry for the miss on the performance, might be a difference on my aging CPU on my dev pc but not on newer hardware.
