### ISSUE TITLE
build options C++ "java-like" (gcc)

### ISSUE THREAD

**Issue by igouy** [frol/completely-unscientific-benchmarks#63]
_afaict_ on old Q6600 **not using** `-flto` is a little more than 0.1s faster.

`main-naive-java-like.cpp`

```
$ /usr/bin/g++ -O3 --std=c++17 -flto -s -o unsci_run unsci.c++
$ time ./unsci_run
331665
real	0m0.756s
user	0m0.755s
sys	0m0.000s
```

```
$ /usr/bin/g++ -O3 --std=c++17 -s -o unsci_run unsci.c++
$ time ./unsci_run
331665
real	0m0.634s
user	0m0.634s
sys	0m0.000s
```

**Comment by igouy** [comment]
The tuning options that you've added make things worse not better than the simpler:

`/usr/bin/g++ -O3 --std=c++17 -o unsci_run unsci.c++`

**Comment by frol** [comment]
Originally, we had no LTO, but most of the solutions benefit from LTO (including this java-like solution using clang compiler), so to keep things simple we decided to use LTO when it is available.

**Comment by igouy** [comment]
Then you need to say that you're making the gcc times slower deliberately.

**Comment by frol** [comment]
It is gcc makes the solution slower, not me. By the way, it is not "times slower", on my machine it is 0.372s (with LTO) vs 0.368s (without LTO), so given I report the execution time rounded to the second meaningful digit, it is still 0.37s either way.

This is GCC 8.1.1.
