### ISSUE TITLE
add ` --stacktrace:off` to guidelines (can have 6X impact)

### ISSUE THREAD

**Issue by timotheecour** [frol/completely-unscientific-benchmarks#65]
see https://github.com/nim-lang/Nim/issues/8959 for context:

even if --stacktrace:off is default, it may be in user's nim.cfg

**Comment by frol** [comment]
I don't see any measured performance boost, so I am not going to add this flag to the guidelines. If this is an important trick, I recommend to highlight it in Nim documentation.

Thanks for your contribution!

**Comment by timotheecour** [comment]
I'm pretty sure the test in https://github.com/nim-lang/Nim/issues/8959 is reproducible, it happens when you have `+=` with floats in a hot-spot.
Perhaps the benchmarks don't have code that involves that.
In any case, I've demonstrated impact can be > 6X in this case. I won't insist more :)
