### ISSUE TITLE
Update Nim to 0.19

### ISSUE THREAD

**Issue by mratsim** [frol/completely-unscientific-benchmarks#66]
Can you redo the benchmark with Nim 0.19?

Several improvements were added especially this one https://github.com/nim-lang/Nim/issues/8745 is partially addressed, Nim was zero-ing memory needlessly when constructing the `(Node, Node)` (tuple of ref types) result value.

I've noticed perf degradation of 30% to 6x, and 1.82x on this specific bench.

Thank you!

**Comment by frol** [comment]
I will do this!

**Comment by frol** [comment]
Updated in https://github.com/frol/completely-unscientific-benchmarks/commit/ebd73814f90d94ef0d1be0a1c3ed4485a0760b03
