### ISSUE TITLE
Which C++ program goes with which results?

### ISSUE THREAD

**Issue by igouy** [frol/completely-unscientific-benchmarks#88]
Is  C++ "tuned raw pointers" (gcc)` this program -- `main-tuned-raw.cpp` -- or is it this  program -- `main-tuned-unique_ptr.cpp` or some other program ?

Please just use the same labels in the results table as you name the programs.

**Comment by frol** [comment]
tuned-raw.cpp is “tuned raw pointers”. How can it be unique_ptr?
